import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatCm } from "../utils/cm-format";
export function FloorSelectorCard({ floorNames, selectedFloorPlanId, activeFloorSizeText, isEditorMode, onSelectFloor, onCreateFloor, }) {
    return (_jsxs("div", { className: "rounded-2xl border border-slate-900/10 bg-white/90 p-3 shadow-[0_10px_24px_rgba(15,23,42,0.08)]", children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsx("p", { className: "m-0 text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500", children: "Floor" }), _jsx("button", { type: "button", className: "rounded-full border border-sky-600 bg-sky-600 px-3 py-1.5 text-xs font-semibold text-white shadow-sm", onClick: onCreateFloor, disabled: isEditorMode, children: "+ floor" })] }), floorNames.length > 0 ? (_jsxs("div", { className: "mt-3 flex items-start justify-between gap-3", children: [_jsx("div", { className: "min-w-0 flex-1", children: _jsx("div", { className: "flex flex-wrap gap-x-3 gap-y-2", children: floorNames.map((floorPlan) => (_jsx("button", { type: "button", onClick: () => onSelectFloor(floorPlan.id), disabled: isEditorMode, className: `min-w-0 max-w-full px-1 py-1 text-left text-sm font-semibold leading-tight transition-colors ${selectedFloorPlanId === floorPlan.id
                                    ? "text-slate-900"
                                    : "text-slate-500"} disabled:cursor-not-allowed disabled:opacity-50`, children: _jsx("span", { className: "break-words", children: floorPlan.name }) }, floorPlan.id))) }) }), activeFloorSizeText ? (_jsx("p", { className: "m-0 shrink-0 self-start rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-semibold text-slate-600", children: activeFloorSizeText })) : null] })) : (_jsxs("div", { className: "min-w-0 pt-3", children: [_jsx("p", { className: "m-0 text-sm font-semibold text-slate-900", children: "No floor plans yet" }), _jsx("p", { className: "m-0 mt-1 text-sm text-slate-500", children: "Create your first floor to start building the map." })] }))] }));
}
export function PreviewHelpCard({ hasActiveFloor }) {
    return (_jsx("div", { className: "rounded-2xl border border-slate-900/10 bg-white/85 p-3 shadow-[0_10px_24px_rgba(15,23,42,0.08)]", children: _jsx("p", { className: "m-0 text-sm font-medium text-slate-600", children: hasActiveFloor
                ? "Tap edit to pan and zoom the selected floor in fullscreen."
                : "Create a floor plan first, then edit zones on that floor." }) }));
}
export function EmptyFloorPreviewCard({ onCreateFloor, }) {
    return (_jsxs("div", { className: "rounded-[24px] border border-dashed border-slate-300 bg-white/70 px-6 py-10 text-center shadow-[0_10px_24px_rgba(15,23,42,0.06)]", children: [_jsx("p", { className: "m-0 text-base font-semibold text-slate-900", children: "No floor selected" }), _jsx("p", { className: "m-0 mt-2 text-sm text-slate-500", children: "Create a floor plan to start drawing zones and editing the map." }), _jsx("button", { type: "button", className: "mt-4 rounded-full bg-sky-600 px-4 py-2 text-sm font-semibold text-white", onClick: onCreateFloor, children: "Create floor" })] }));
}
export function ZonesListCard({ zones, hasActiveFloor, onNormalize, onDelete, }) {
    return (_jsxs("div", { className: "rounded-2xl border border-slate-900/10 bg-white/90 p-3 shadow-[0_10px_24px_rgba(15,23,42,0.08)]", children: [_jsxs("div", { className: "mb-3 flex items-center justify-between", children: [_jsx("p", { className: "m-0 text-sm font-semibold text-slate-900", children: "Zones" }), _jsx("button", { type: "button", className: "rounded-full border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600", onClick: onNormalize, children: "Normalize order" })] }), _jsx("div", { className: "flex flex-col gap-2", children: zones.length > 0 ? (zones.map((zone) => (_jsxs("div", { className: "flex items-center justify-between rounded-xl border border-slate-900/10 bg-slate-50/70 px-3 py-2", children: [_jsxs("div", { children: [_jsx("p", { className: "m-0 text-sm font-semibold text-slate-900", children: zone.label }), _jsxs("p", { className: "m-0 mt-1 text-xs text-slate-500", children: [zone.type, " \u00B7 ", zone.xPct.toFixed(1), "%, ", zone.yPct.toFixed(1), "%", zone.widthCm && zone.depthCm
                                            ? ` · ${formatCm(zone.widthCm)} × ${formatCm(zone.depthCm)}`
                                            : ""] })] }), _jsx("button", { type: "button", className: "rounded-full border border-rose-200 px-3 py-1.5 text-xs font-semibold text-rose-600", onClick: () => onDelete(zone.id), children: "Delete" })] }, zone.id)))) : (_jsx("p", { className: "m-0 text-sm text-slate-500", children: hasActiveFloor
                        ? "No zones on this floor yet."
                        : "Create a floor first to manage zones." })) })] }));
}
