import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatBootstrapSyncLabel, settingsOptionSubscriptions, } from "../domain/settings-options.domain";
import { useSettingsPageContext } from "../context/settings-page-context";
import { SettingsOptionRow } from "./SettingsOptionRow";
import { SettingsProfileCard } from "./SettingsProfileCard";
export function SettingsPage() {
    const { profile, isProfileLoading, profileError, bootstrapLastSyncedAt, scannerOnScanAsk, isLogoutPending, logoutError, openOption, setScannerOnScanAsk, logout, } = useSettingsPageContext();
    return (_jsxs("section", { className: "mx-auto flex min-h-[calc(100svh-7.5rem)] w-full max-w-[720px] flex-col gap-4 px-4 pb-32 pt-6", children: [_jsxs("header", { children: [_jsx("p", { className: "m-0 text-xs uppercase tracking-[0.08em] text-slate-500", children: "Workspace" }), _jsx("h1", { className: "m-0 mt-1 text-3xl font-black text-slate-900", children: "Settings" }), bootstrapLastSyncedAt ? (_jsxs("p", { className: "m-0 mt-1 text-xs font-medium text-slate-500", children: ["Bootstrap last synced:", " ", formatBootstrapSyncLabel(bootstrapLastSyncedAt)] })) : null] }), isProfileLoading ? (_jsx("div", { className: "h-[86px] animate-pulse rounded-2xl border border-slate-900/10 bg-white/70" })) : profile ? (_jsx(SettingsProfileCard, { username: profile.username, role: profile.role })) : (_jsx("div", { className: "rounded-xl bg-rose-100 px-3 py-2 text-sm font-medium text-rose-900", children: profileError ?? "Unable to load profile details." })), _jsx("div", { className: "mt-2 flex flex-col gap-3", children: settingsOptionSubscriptions.map((option) => (_jsx(SettingsOptionRow, { label: option.label, onPress: () => openOption(option.id) }, option.id))) }), _jsx("div", { className: "rounded-xl border border-slate-900/10 bg-white/85 p-3 shadow-[0_10px_22px_rgba(15,23,42,0.06)]", children: _jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "m-0 text-sm font-semibold text-slate-900", children: "Ask before location scan" }), _jsx("p", { className: "m-0 mt-1 text-xs text-slate-500", children: "When enabled, item scan stays on this step until you tap Scan location." })] }), _jsxs("label", { className: "inline-flex cursor-pointer items-center", children: [_jsx("input", { type: "checkbox", className: "peer sr-only", checked: scannerOnScanAsk, onChange: (event) => setScannerOnScanAsk(event.currentTarget.checked), "aria-label": "Ask before location scan" }), _jsx("span", { className: `relative h-6 w-11 rounded-full transition peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-emerald-500 ${scannerOnScanAsk ? "bg-emerald-500" : "bg-slate-300"}`, children: _jsx("span", { className: `absolute top-0.5 h-5 w-5 rounded-full bg-white shadow-sm transition-all ${scannerOnScanAsk ? "left-[22px]" : "left-0.5"}` }) })] })] }) }), _jsxs("div", { className: "mt-auto pt-4", children: [logoutError ? (_jsx("div", { className: "mb-3 rounded-xl border border-rose-300 bg-rose-100 px-3 py-2 text-sm font-medium text-rose-900", children: logoutError })) : null, _jsx("button", { type: "button", className: "h-11 w-full rounded-xl border border-rose-200 bg-rose-50 text-sm font-bold text-rose-700 transition hover:bg-rose-100 disabled:cursor-not-allowed disabled:opacity-70", onClick: () => void logout(), disabled: isLogoutPending, children: isLogoutPending ? "Logging out..." : "Log out" })] })] }));
}
