import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { BackArrowIcon, FlasklightIcon, WriteIcon, } from "../../../assets/icons";
export function ScannerActionsOverlay({ stepTitle, flashEnabled, availableLenses, selectedLensId, headerActionLabel, onHeaderAction, onBack, onToggleFlash, onSelectLens, onManualInput, }) {
    const iconActionClass = "grid h-10 w-10 place-items-center rounded-full bg-slate-950/40 text-slate-100 ring-1 ring-white/25";
    return (_jsxs(_Fragment, { children: [_jsxs("header", { className: "absolute inset-x-0 top-0 z-30 flex items-center justify-start px-4 pb-3", style: { paddingTop: "max(1rem, env(safe-area-inset-top))" }, children: [_jsx("button", { type: "button", className: iconActionClass, onClick: onBack, "aria-label": "Back", children: _jsx(BackArrowIcon, { className: "h-4 w-4", "aria-hidden": "true" }) }), _jsx("div", { className: "pointer-events-none absolute left-1/2 -translate-x-1/2 rounded-full bg-slate-950/40 px-4 py-2 text-sm font-semibold text-slate-100", children: stepTitle }), headerActionLabel && onHeaderAction ? (_jsx("button", { type: "button", className: `${iconActionClass} absolute right-4 top-[max(1rem,env(safe-area-inset-top))]`, onClick: onHeaderAction, "aria-label": headerActionLabel, title: headerActionLabel, children: _jsx(BackArrowIcon, { className: "h-4 w-4 rotate-180", "aria-hidden": "true" }) })) : null] }), _jsx("footer", { className: "absolute inset-x-0 bottom-0 z-30 px-4 pt-3", style: {
                    paddingBottom: "max(1rem, env(safe-area-inset-bottom))",
                }, children: _jsxs("div", { className: "relative h-11", children: [_jsx("button", { type: "button", className: `${iconActionClass} absolute left-0 top-0 ${flashEnabled
                                ? "!bg-sky-900 ring-2 ring-sky-300/70"
                                : "bg-slate-950/40"}`, onClick: onToggleFlash, "aria-label": flashEnabled ? "Flash on" : "Flash off", children: _jsx(FlasklightIcon, { className: "h-5 w-5", "aria-hidden": "true" }) }), availableLenses.length > 1 ? (_jsx("div", { className: "absolute left-1/2 top-1/2 flex -translate-x-1/2 -translate-y-1/2 gap-1 rounded-full bg-slate-950/55 p-1", role: "group", "aria-label": "Camera lenses", children: availableLenses.map((lens) => (_jsx("button", { type: "button", className: `min-h-8 min-w-9 rounded-full px-2 text-xs font-semibold ${selectedLensId === lens.id
                                    ? "bg-sky-100 text-sky-900"
                                    : "text-sky-100"}`, onClick: () => onSelectLens(lens.id), children: lens.label }, lens.id))) })) : null, _jsx("button", { type: "button", className: `${iconActionClass} absolute right-0 top-0`, onClick: onManualInput, "aria-label": "Manual input", children: _jsx(WriteIcon, { className: "h-6 w-6", "aria-hidden": "true" }) })] }) })] }));
}
